# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Injoker"
license = "MIT"
licenselink = "https://github.com/tanlinhnd/hugo-injoker-theme/blob/master/LICENSE.md"
description = "Injoker minimal responsive theme"
homepage = "https://github.com/tanlinhnd/hugo-injoker-theme"
tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
  name = "Tan Linh"
  homepage = "https://imlinh.com/"
[original]
    author = "Jonathan Rutheiser"
    homepage = "http://jrutheiser.com/"
    repo = "https://github.com/jrutheiser/hugo-lithium-theme"

